<template>
  <section class="wrapper">
    <section class="wrap">
      <el-table border stripe :data="info">
        <el-table-column v-if="$route.path === '/check'" type="selection" align="center" width='80'></el-table-column>
        <el-table-column v-if="$route.path === '/letter' || $route.path == '/index/message'" type="index" align="center" label="序号" width='80'></el-table-column>
        <el-table-column v-if="item.type === 'expand'" type="expand" align='center' v-for="(item,index) in dataList" :key="index" :label="item.key">
          <template slot-scope="scope">
            <el-table :data="scope.row.scoreInfoList" border stripe>
              <el-table-column align="center" v-if="sub.type === 'default'" v-for="(sub,sin) in subDataList" :key="sin" :label="sub.key" :prop="sub.prop"></el-table-column>
            </el-table>
          </template>
        </el-table-column>
        <el-table-column v-if="item.type === 'default'" align="center" v-for="(item,index) in dataList" :key="index" :label="item.key" :prop="item.prop"></el-table-column>
        <el-table-column fixed="right" v-if="item.type === 'button'" align='center' v-for="(item,index) in dataList" :key="index" :label="item.key">
          <template slot-scope="scope">
              <el-button v-for="(btn,bin) in item.list" :key="bin" :type="btn.type" @click="btn.click(scope)">{{btn.text}}</el-button>
          </template>
        </el-table-column>
      </el-table>
    </section>
  </section>
</template>


<script>
export default {
  props:['info'],
  data(){
    return{
      data:[
        {
          name:'index',
          data:[
            {
              key:'工号',
              prop:'number',
              type:'default',
            },
            {
              key:'姓名',
              prop:'name',
              type:'default',
            },
            {
              key:'职务',
              prop:'administrative',
              type:'default',
            },
            {
              key:'管辖班级',
              prop:'scope',
              type:'default',
            },
            {
              key:'联系电话',
              prop:'tel',
              type:'default',
            },
            {
              key:'QQ',
              prop:'qq',
              type:'default',
            },
            {
              key:'微信',
              prop:'wechat',
              type:'default',
            },
            {
              key:'邮箱',
              prop:'email',
              type:'default',
            },
            {
              key:'办公地址',
              prop:'address',
              type:'default',
            }
          ]
        },
        {
          name:'check',
          data:[
            {
              key:'姓名',
              prop:'name',
              type:'default'
            },
            {
              key:'专业班级',
              prop:'klass',
              type:'default'
            },
            {
              key:'学号',
              prop:'number',
              type:'default'
            },
            {
              key:'考勤类型',
              prop:'check_type',
              type:'default'
            },
            {
              key:'迟到',
              prop:'later',
              type:'default'
            },
            {
              key:'旷课',
              prop:'out',
              type:'default'
            },
            {
              key:'请假',
              prop:'leave',
              type:'default'
            },
            {
              key:'出勤率',
              prop:'check_rota',
              type:'default'
            },
            {
              key:'操作',
              type:'button',
              list:[
                {
                  text:'查看',
                  click:'',
                  type:'text'
                }
              ]
            }
          ]
        },
        {
          name:'grade',
          data:[
            {
              key:'姓名',
              prop:'name',
              type:'default',
            },
            {
              key:'专业班级',
              prop:'classes',
              type:'default',
            },
            {
              key:'学号',
              prop:'number',
              type:'default',
            },
            {
              key:'平均成绩',
              prop:'averageScore',
              type:'default',
            },
            {
              key:'班级排名',
              prop:'classRank',
              type:'default',
            },
            {
              key:'年级排名',
              prop:'gradeRank',
              type:'default',
            },
            {
              key:'所得学分',
              prop:'credit',
              type:'default',
            },
            {
              key:'挂科门数',
              prop:'failCount',
              type:'default',
            },
            {
              key:'操作',
              type:'button',
              list:[
                {
                  text:'编辑',
                  type:'text',
                  click:''
                },
                {
                  text:'详情',
                  type:'text',
                  click:''
                }
              ]
            }
          ]
        },
        {
          name:'fails',
          data:[
            {
              key:'',
              type:'expand',
            },
            {
              key:'姓名',
              prop:'name',
              type:'default',
            },
            {
              key:'班级',
              prop:'classes',
              type:'default',
            },
            {
              key:'学号',
              prop:'number',
              type:'default',
            },
            {
              key:'累计挂科',
              prop:'failCount',
              type:'default',
            },
          ]
        },
        {
          name:'letter',
          data:[
            {
              key:'名称',
              prop:'name',
              type:'default',
            },
            {
              key:'发布时间',
              prop:'time',
              type:'default',
            },
            {
              key:'操作',
              type:'button',
              list:[
                {
                  text:'查看发送对象',
                  type:'text',
                  click:''
                },
                {
                  text:'查看详情',
                  type:'text',
                  click:''
                }
              ]
            }
          ]
        },
        {
          name:'setting',
          data:[
            {
              key:'姓名',
              prop:'name',
              type:'default'
            },
            {
              key:'工号',
              prop:'number',
              type:'default'
            },
            {
              key:'职能',
              prop:'position',
              type:'default'
            },
            {
              key:'职能范围',
              prop:'scope',
              type:'default'
            },
            {
              key:'操作',
              type:'button',
              list:[
                {
                  text:'删除',
                  click:this.handleClickDelById,
                  type:'text'
                },
                {
                  text:'更改',
                  click:this.handleClickEdit,
                  type:'text'
                }
              ]
            },            
          ]
        },
        {
          name:'leave',
          data:[
              {
                key:'名称',
                prop:'name',
                type:'default',
              },
              {
                key:'发布时间',
                prop:'time',
                type:'default',
              },
              {
                key:'操作',
                type:'button',
                list:[
                  {
                    text:'查看发送对象',
                    type:'text',
                    click:''
                  },
                  {
                    text:'查看详情',
                    type:'text',
                    click:''
                  }
                ]
              }
            ]
          },
        {
          name:'student',
          data:[
            {
              key:'姓名',
              prop:'name',
              type:'default',
            },
            {
              key:'专业班级',
              prop:'classes',
              type:'default',
            },
            {
              key:'学号',
              prop:'number',
              type:'default',
            },
            {
              key:'电话',
              prop:'phone',
              type:'default',
            },
            {
              key:'身份证号',
              prop:'no',
              type:'default',
            },
            {
              key:'是否关联',
              prop:'isRelevance',
              type:'default',
            },
            {
              key:'关联账号',
              prop:'userId',
              type:'default',
            },
            {
              key:'联系电话',
              prop:'userPhone',
              type:'default',
            },
            {
              key:'操作',
              type:'button',
              list:[
                {
                  text:'解除',
                  click:'',
                  type:'text'
                },
                {
                  text:'更改',
                  click:'',
                  type:'text'
                }
              ]
            }
          ]
        },
        {
          name:'message',
          data:[
            {
              key:'序号',
              type:'index',
            },
            {
              key:'消息名',
              type:'default',
              prop:'name',
            },
            {
              key:'发布时间',
              type:'default',
              prop:'time',
            },
            {
              key:'操作',
              type:'button',
              list:[
                {
                  text:'查看',
                  click:'',
                  type:'text'
                }
              ]
            }
          ]
        }
      ],
      subData:[
        {
          name:'fails',
          data:[
            {
              key:'课程名',
              prop:'className',
              type:'default',
            },
            {
              key:'分数',
              prop:'score',
              type:'default',
            },
            {
              key:'学分',
              prop:'credit',
              type:'default',
            },
            {
              key:'考试时间',
              prop:'examTime',
              type:'default',
            }
          ]
        }
      ]
    }
  },
  computed:{
    NAME(){
      return this.$route.name
    },
    dataList(){
      return this.data && this.data.find(item => item.name == this.NAME) 
                && this.data.find(item => item.name == this.NAME).data
    },
    subDataList(){
      return this.data && this.subData.find(item => item.name == this.NAME) 
                && this.subData.find(item => item.name == this.NAME).data
    }
  },
  methods:{
    /**
     * 单击编辑 -- 操作事件
     */
    handleClickEdit(e){
      this.$emit('getRowData',e.row)
    },

    /**
     * 单击删除 -- 操作事件
     */
    handleClickDelById(e){
      this.$store.dispatch('delSettingAvatars',{id:e.row.id}).then(()=>{
        this.$store.dispatch('getSettingsAvatars',{currPageNo:1})
      })
    },
  },
}
</script>


<style lang="less" scoped>

</style>
