<template>
  <section class="wrapper">
    <section class="wrap">
      <el-table @selection-change="handelSelectionChange" border stripe ref="mytable" :data="info">
        <el-table-column v-if="$route.path === '/check' && !type" type="selection" align="center" width='80'></el-table-column>
        <el-table-column v-if="isShowSelection" type="selection" align="center" width='80'></el-table-column>
        <el-table-column v-if="$route.path === '/check' && type" type="index" align="center" width='80' label="序号"></el-table-column>
        <el-table-column v-if="$route.path === '/letter' || $route.path == '/index/message'" type="index" align="center" label="序号" width='80'></el-table-column>
        <el-table-column v-if="item.type === 'expand' && !isShowSelection" type="expand" align='center' v-for="(item,index) in dataList" :key="index" :label="item.key">
          <template slot-scope="scope">
            <el-table :data="scope.row.scoreInfoList" border stripe>
              <el-table-column align="center" v-if="sub.type === 'default'" v-for="(sub,sin) in subDataList" :key="sin" :label="sub.key" :prop="sub.prop"></el-table-column>
            </el-table>
          </template>
        </el-table-column>
        <el-table-column v-if="item.type === 'default'" align="center" v-for="(item,index) in dataList" :key="index" :label="item.key" :prop="item.prop"></el-table-column>
        <el-table-column fixed="right" v-if="item.type === 'button'" align='center' v-for="(item,index) in dataList" :key="index" :label="item.key">
          <template slot-scope="scope">
              <el-button v-for="(btn,bin) in item.list" :key="bin" :type="btn.type" @click="btn.click(scope)">{{btn.text}}</el-button>
          </template>
        </el-table-column>
      </el-table>
     <div v-if="isShowSelection" style="margin-top:15px;">
      <el-button @click="reset" size="small" type="" >取消</el-button>
      <el-button @click="submit" size="small" type="primary" >确定</el-button>
     </div>
    </section>
  </section>
</template>


<script>
export default {
  props:['info','type','isShowSelection'],
  data(){
    return{
      data:[
        {
          name:'index',
          data:[
            {
              key:'工号',
              prop:'number',
              type:'default',
            },
            {
              key:'姓名',
              prop:'name',
              type:'default',
            },
            {
              key:'职务',
              prop:'administrative',
              type:'default',
            },
            {
              key:'管辖班级',
              prop:'scope',
              type:'default',
            },
            {
              key:'联系电话',
              prop:'tel',
              type:'default',
            },
            {
              key:'QQ',
              prop:'qq',
              type:'default',
            },
            {
              key:'微信',
              prop:'wechat',
              type:'default',
            },
            {
              key:'邮箱',
              prop:'email',
              type:'default',
            },
            {
              key:'办公地址',
              prop:'address',
              type:'default',
            }
          ]
        },
        {
          name:'check',
          data:[
            {
              key:'姓名',
              prop:'name',
              type:'default'
            },
            {
              key:'专业班级',
              prop:'classes',
              type:'default'
            },
            {
              key:'学号',
              prop:'number',
              type:'default'
            },
            {
              key:'考勤类型',
              prop:'check_type',
              type:'default'
            },
            {
              key:'迟到',
              prop:'late',
              type:'default'
            },
            {
              key:'旷课',
              prop:'cut',
              type:'default'
            },
            {
              key:'请假',
              prop:'leave',
              type:'default'
            },
            {
              key:'出勤率',
              prop:'rate',
              type:'default'
            },
            {
              key:'操作',
              type:'button',
              list:[
                {
                  text:'查看',
                  click:this.handleClickWithDialog,
                  type:'text'
                }
              ]
            }
          ]
        },
        {
          name:'grade',
          data:[
            {
              key:'姓名',
              prop:'name',
              type:'default',
            },
            {
              key:'专业班级',
              prop:'classes',
              type:'default',
            },
            {
              key:'学号',
              prop:'number',
              type:'default',
            },
            {
              key:'平均成绩',
              prop:'averageScore',
              type:'default',
            },
            {
              key:'班级排名',
              prop:'classRank',
              type:'default',
            },
            {
              key:'年级排名',
              prop:'gradeRank',
              type:'default',
            },
            {
              key:'所得学分',
              prop:'credit',
              type:'default',
            },
            {
              key:'挂科门数',
              prop:'failCount',
              type:'default',
            },
            {
              key:'操作',
              type:'button',
              list:[
                {
                  text:'编辑',
                  type:'text',
                  click:this.handleClickWithDialog,
                },
                {
                  text:'详情',
                  type:'text',
                  click:this.handleClickDetail
                }
              ]
            }
          ]
        },
        {
          name:'fails',
          data:[
            {
              key:'',
              type:'expand',
            },
            {
              key:'姓名',
              prop:'name',
              type:'default',
            },
            {
              key:'班级',
              prop:'classes',
              type:'default',
            },
            {
              key:'学号',
              prop:'number',
              type:'default',
            },
            {
              key:'累计挂科',
              prop:'failCount',
              type:'default',
            },
          ]
        },
        {
          name:'letter',
          data:[
            {
              key:'学期',
              prop:'quarter',
              type:'default',
            },
            {
              key:'发布时间',
              prop:'createTime',
              type:'default',
            },
            {
              key:'操作',
              type:'button',
              list:[
                {
                  text:'查看发送对象',
                  type:'text',
                  click:''
                },
                {
                  text:'查看详情',
                  type:'text',
                  click:this.jump2Detail
                }
              ]
            }
          ]
        },
        {
          name:'setting',
          data:[
            {
              key:'姓名',
              prop:'name',
              type:'default'
            },
            {
              key:'工号',
              prop:'number',
              type:'default'
            },
            {
              key:'职能',
              prop:'position',
              type:'default'
            },
            {
              key:'职能范围',
              prop:'scope',
              type:'default'
            },
            {
              key:'操作',
              type:'button',
              list:[
                {
                  text:'删除',
                  click:this.handleClickDelById,
                  type:'text'
                },
                {
                  text:'更改',
                  click:this.handleClickEdit,
                  type:'text'
                }
              ]
            },            
          ]
        },
        {
          name:'leave',
          data:[
              {
                key:'类型',
                prop:'type',
                type:'default',
              },
              {
                key:'标题',
                prop:'title',
                type:'default',
              },
              {
                key:'发布时间',
                prop:'createTime',
                type:'default',
              },
              {
                key:'操作',
                type:'button',
                list:[
                  {
                    text:'查看发送对象',
                    type:'text',
                    click:''
                  },
                  {
                    text:'查看详情',
                    type:'text',
                    click:this.jump2Detail
                  }
                ]
              }
            ]
          },
        {
          name:'student',
          data:[
            {
              key:'姓名',
              prop:'name',
              type:'default',
            },
            {
              key:'专业班级',
              prop:'classes',
              type:'default',
            },
            {
              key:'学号',
              prop:'number',
              type:'default',
            },
            {
              key:'电话',
              prop:'phone',
              type:'default',
            },
            {
              key:'身份证号',
              prop:'no',
              type:'default',
            },
            {
              key:'是否关联',
              prop:'isRelevance',
              type:'default',
            },
            {
              key:'关联账号',
              prop:'userId',
              type:'default',
            },
            {
              key:'联系电话',
              prop:'userPhone',
              type:'default',
            },
            {
              key:'操作',
              type:'button',
              list:[
                {
                  text:'解除',
                  click:this.handleClickDelById,
                  type:'text'
                },
                {
                  text:'更改',
                  click:this.handleClickWithDialog,
                  type:'text'
                }
              ]
            }
          ]
        },
        {
          name:'message',
          data:[
            {
              key:'序号',
              type:'index',
            },
            {
              key:'消息内容',
              type:'default',
              prop:'content',
            },
            {
              key:'发布时间',
              type:'default',
              prop:'createTime',
            },
            {
              key:'操作',
              type:'button',
              list:[
                {
                  text:'查看',
                  click:this.jump2Detail,
                  type:'text'
                }
              ]
            }
          ]
        },
        {
          name:'guideList',
          data:[
            {
              key:'序号',
              type:'index',
            },
            {
              key:'标题',
              type:'default',
              prop:'title',
            },
            {
              key:'内容',
              type:'default',
              prop:'content',
            },
            {
              key:'发布时间',
              type:'default',
              prop:'createTime'
            },
            {
              key:'操作',
              type:'button',
              list:[
                {
                  text:'查看',
                  type:'text',
                  click:this.jump2Detail
                },
                {
                  text:'更新',
                  type:'text',
                  click:this.handleTumpToEditForGuide
                }
              ]
            }
          ]
        },
        {
          type:'message1',
          data:[
            {
              key:'序号',
              type:'index'
            },
            {
              key:'意见内容',
              prop:'feedContent',
              type:'default'
            },
            {
              key:'提交时间',
              prop:'feedTime',
              type:'default'
            },
            {
              key:'回复内容',
              prop:'replyContent',
              type:'default',
            },
            {
              key:'回复时间',
              prop:'replyTime',
              type:'default'
            }
          ]
        },
        {
          type:'check1',
          data:[
            {
              key:'序号',
              type:'index',
            },
            {
              key:'发起类型',
              type:'default',
              prop:'type',
            },
            {
              key:'发起时间',
              type:'default',
              prop:'fomTime',
            },
            {
              key:'发起次数',
              type:'default',
              prop:'state',
            },
            {
              key:'发起教师',
              type:'default',
              prop:'teacherName',
            }
          ]
        },
        {
          type:'check2',
          data:[
            {
              key:'标题',
              type:'default',
              prop:'title',
            },
            {
              key:'发起时间',
              type:'default',
              prop:'fomTime',
            },
            {
              key:'发起次数',
              type:'default',
              prop:'state',
            },
            {
              key:'发起教师',
              type:'default',
              prop:'teacherName'
            }
          ]
        },
        {
          type:'check3',
          data:[
            {
              key:'标题',
              type:'default',
              prop:'title',
            },
            {
              key:'发起类型',
              type:'default',
              prop:'type',
            },
            {
              key:'发起时间',
              type:'default',
              prop:'fomTime',
            },
            {
              key:'发起次数',
              type:'default',
              prop:'state',
            },
            {
              key:'发起教师',
              type:'default',
              prop:'teacherName'
            }
          ]
        }
      ],
      subData:[
        {
          name:'fails',
          data:[
            {
              key:'课程名',
              prop:'className',
              type:'default',
            },
            {
              key:'分数',
              prop:'score',
              type:'default',
            },
            {
              key:'学分',
              prop:'credit',
              type:'default',
            },
            {
              key:'考试时间',
              prop:'examTime',
              type:'default',
            }
          ]
        }
      ],
      checkList:[]
    }
  },
  computed:{
    NAME(){
      return this.$route.name
    },
    dataList(){
      if(!this.type){
        return this.data && this.data.find(item => item.name == this.NAME) 
                && this.data.find(item => item.name == this.NAME).data
      }else{
        return this.data && this.data.find(item => item.type == this.type)
                && this.data.find(item => item.type == this.type).data
      }
    },
    subDataList(){
      return this.data && this.subData.find(item => item.name == this.NAME) 
                && this.subData.find(item => item.name == this.NAME).data
    }
  },
  methods:{
    /**
     * 表格选中变化
     */
    handelSelectionChange(e){
      this.checkList = e
    },
    submit(){
      this.$prompt('请编辑内容','编辑',{
        confirmButtonText:'确定',
        cancelButtonText:'取消',
      }).then(({value})=>{
        let numbers = JSON.stringify(this.checkList)
        this.$store.dispatch('handleSendNotice',{numbers:numbers,content:value}).then((res)=>{
          setTimeout(()=>{
            this.reset()
          },1000)
        })
      })
    },
    reset(){
      this.$refs.mytable.clearSelection()
      this.$emit('getResetMsg',{isShowDialog:false})
    },
    /**
     * 更新 -- 发布页 -- 招生简章
     */
    handleTumpToEditForGuide(e){
      this.$router.push({path:'/guide'})
    },
    /**
     * 查看详情至详情页
     */
    jump2Detail(e){
      let RootPath = this.$route.path , path = '' , query = {}
      switch(RootPath){
        case '/index/leave' : path = '/index/leave/detail' , query = {id:e.row.id} 
          break;
        case '/index/message' : path = '/index/message/detail' , query = {id:e.row.id}
          break;
        case '/guide/list' : path = '/guide/list/detail' , query = {id:e.row.id}
          break;
        case '/letter' : path = '/letter/detail' , query = {id:e.row.id}
          break; 
      }
      this.$router.push({path:path , query:query})
    },
    /**
     * 单击编辑 -- 操作事件
     */
    handleClickEdit(e){
      this.$emit('getRowData',e.row)
    },

    /**
     * 查看详情
     */
    handleClickDetail(e){
      this.$emit('getDetailInfo',{isShowDetail:true,data:e.row})
    },

    /**
     * 单击编辑 -- 伴随着dialog对话框
     */
    handleClickWithDialog(e){
      this.$emit('getRowDataWithDialog',{data:e.row,isShowDialog:true})
    },

    

    /**
     * 单击删除 -- 操作事件
     */
    handleClickDelById(e){
      let _del = '' , _get = '' , data = {}
      switch(this.NAME){
        case 'student' : _del = 'delStudentConcat' , _get = 'getStudentList' , data = {userId:e.row.userId}
          break;
        case 'setting' : _del = 'delSettingAvatars' , _get = 'getSettingsAvatars' , data = {id:e.row.id}
          break;
      }
      this.$confirm('这是一条删除操作,是否继续?','提示',{
        confirmButtonText:'确定',
        cancelButtonText:'取消',
        type:'warning'
      }).then(()=>{
        this.$store.dispatch(_del,data).then(()=>{
          this.$store.dispatch(_get)
        })
      }).catch(()=>{
        _g.toastMsg('warning','操作已取消')
      })
    },
  },
  created(){
 
  }
}
</script>


<style lang="less" scoped>

</style>
